services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      target: workspace
    user: node
    volumes:
      - ..:/workspace/arkord:cached
      - node_modules:/workspace/arkord/infra/node_modules
    tty: true
    init: true

volumes:
  node_modules:
