name: CI (Infra)

on:
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/ci_infra.yml'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  ci_infra:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read node version from Dockerfile
        run: echo ::set-output name=node_version::$(grep -P -o '(?<=node:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
        id: node_version

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.node_version }}
          cache: npm
          cache-dependency-path: infra/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc-arkord-ci
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Check diff
        id: diff
        run: |
          npm run diff | tee cdk-diff
          out="$(cat cdk-diff)"
          out="${out//'%'/'%25'}"
          out="${out//$'\n'/'%0A'}"
          out="${out//$'\r'/'%0D'}"
          echo "::set-output name=stdout::$out"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Diff output

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## :police_officer: Diff output

            ```console
            ${{ steps.diff.outputs.stdout }}
            ```
          edit-mode: replace
